### ISSUE TITLE
Update for Laravel 5.x support

### ISSUE THREAD

**Issue by Braunson** [Braunson/laravel-rackspace-cdn#1]

**Comment by fragkp** [comment]
reserved ;)

**Comment by Braunson** [comment]
@fragkp You wanted to take on this? Why delete your comment?

**Comment by fragkp** [comment]
Sry, but without any tests, its to hard to upgrade to Laravel 5.5

**Comment by defaultpage** [comment]
Hi! Can you give me username and apiKey for manual testing? I think the code is ready (except refactoring and docs)...

**Comment by Braunson** [comment]
@ArtemMolotov I no longer use RackSpace and don't subsequently have an account.
