### ISSUE TITLE
Invalid package refference laravel-rackspace-opencloud

### ISSUE THREAD

**Issue by wfrackiewicz** [Braunson/laravel-rackspace-cdn#2]
Hello,
In some places like readme the package name is invalid. It says laravel-rackspace-opencloud but that's not a big issue.
in file CdnSyncCommand.php it tries to get the config from:
$container_name = \Config::get('laravel-rackspace-opencloud::container');

Where I think it should
$container_name = \Config::get('laravel-rackspace-cdn::container');

**Comment by Braunson** [comment]
Thanks @wfrackiewicz adjusted.
