### ISSUE TITLE
Incorrect facade alias and namespaces

### ISSUE THREAD

**Issue by defaultpage** [Braunson/laravel-rackspace-cdn#3]
#2 870275490ed4476de3ef7f4c0f5f9b97f5e18709:

> "providers": [
>   "Braunson\\LaravelRackspace**Opencloud**\\LaravelRackspace**Opencloud**ServiceProvider"
> ],
> "aliases": {
>   "Open**c**loud": "Braunson\\LaravelRackspace**Opencloud**\\Facades\\OpenCloud"
> }

`composer update`:
> ...
> \> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> \> @php artisan package:discover
> 
> In ProviderRepository.php line 208:
> 
>   Class 'Braunson\LaravelRackspace**Opencloud**\LaravelRackspace**Opencloud**ServiceProvider' not found

**Comment by Braunson** [comment]
Thanks for fixing this up!
